repos:
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.0.0
        hooks:
        - id: flake8
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 449ace5
        hooks:
        -   id: mypy
            args: [--ignore-missing-imports]